# Generated by Django 3.1 on 2020-08-31 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0003_account'),
    ]

    operations = [
        migrations.DeleteModel(
            name='account',
        ),
    ]
