# Generated by Django 3.1 on 2020-09-01 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0005_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='password',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='permission',
            name='username',
            field=models.TextField(max_length=100),
        ),
    ]
